build:
  environment:
    mysql: 5.7

  dependencies:
    override:
      - composer install --no-interaction

  tests:
    override:
      - command: './bin/phing unit'
        coverage:
          file:   'test/coverage.xml'
          format: 'php-clover'
