language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  
sudo: true

addons:
  mariadb: '10.1'
  
before_install:
  - sudo find /etc -type f -name "*.cnf" -ls -exec cat {} \;
  - sudo service mysql restart
  - mysql -u root -e "create database if not exists test;"
  - mysql -u root -e "create user 'test'@'localhost' identified by 'test';"
  - mysql -u root -e "grant all on test.*  to 'test'@'localhost';"
  - mysql -u root -e "set global binlog_format = 'row';"
  - mysql -u root -e "set global log_bin_trust_function_creators = 1;"
  - mysql -u root -e "show variables;"
  
install:
  - composer self-update
  - composer install
    
script: 
  - ./bin/phing unit
  

