language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  
sudo: true

addons:
  mariadb: '10.0'
  
before_script:
  - echo "binlog_format = row"                 | sudo tee    /etc/mysql/conf.d/row_replication.cnf
  - echo "log_bin_trust_function_creators = 1" | sudo tee -a /etc/mysql/conf.d/row_replication.cnf
  - systemctl restart mysql
  - mysql -u root -e "create database if not exists test;"
  - mysql -u root -e "create user 'test'@'localhost' identified by 'test';"
  - mysql -u root -e "grant all on test.*  to 'test'@'localhost';"
  
install:
  - composer self-update
  - composer install
    
script: 
  - ./bin/phing unit
  

