language: php
php:
  - '5.4'

addons:
  mariadb: '10.0'
  
before_script:
  - mysql -u root -e 'create database if not exists test;'
  - mysql -u root -e "create user 'test'@'localhost' identified by 'test';"
  - mysql -u root -e "grant all on test.*  to 'test'@'localhost';"

install:
    - composer install --dev
    
script: phing unit

