language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

addons:
  mariadb: '10.0'
  
before_script:
  - mysql -u root -e 'create database if not exists test;'
  - mysql -u root -e "create user 'test'@'localhost' identified by 'test';"
  - mysql -u root -e "grant all on test.*  to 'test'@'localhost';"

install:
  - composer self-update
  - composer install --dev
    
script: 
  - ./bin/phing unit
  

