language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
  
sudo: true

env:
  - DB=mysql
  - DB=mariadb100
  - DB=mariadb101
  
mysql:

mariadb100:
  addons:
    mariadb: '10.0'

mariadb101:
  addons:
    mariadb: '10.1'

before_install:
  - mysql -u root -e "create database if not exists test;"
  - mysql -u root -e "create user 'test'@'localhost' identified by 'test';"
  - mysql -u root -e "grant all on test.*  to 'test'@'localhost';"
  - mysql -u root -e "set global binlog_format = 'row';"
  - mysql -u root -e "set global log_bin_trust_function_creators = 1;"
  
install:
  - composer self-update
  - composer install
    
script: 
  - ./bin/phing unit
  

